fix: apply-color script of fastfetch & gcp

diff --git a/config/fastfetch/.config/fastfetch/apply-color b/config/fastfetch/.config/fastfetch/apply-color
--- a/config/fastfetch/.config/fastfetch/apply-color
+++ b/config/fastfetch/.config/fastfetch/apply-color
@@ -1,16 +1,16 @@
 #!/bin/bash
 
 [ -f "$HOME/.local/snippets/apply-color-helper" ] || {
-    echo "Missing helper script: $HOME/.local/snippets/apply-color-helper"
-    exit 1
+	echo "Missing helper script: $HOME/.local/snippets/apply-color-helper"
+	exit 1
 }
 . "$HOME/.local/snippets/apply-color-helper"
 
-file="$HOME/.config/fish/post.d/fetch.fish"
+file="$HOME/.config/fish/conf.d/60-fetch.fish"
 
 sed -i -E "s/(set -g fetch_color\s+\"#)([0-9a-fA-F]{6})(\")/\1${colorHex}\3/" "$file" || {
-    log_error "Failed to edit ${file}"
-    exit 1
+	log_error "Failed to edit ${file}"
+	exit 1
 }
 
 log_success "fastfetch"
