better stow (vielleicht :/

diff --git a/config/scripts/.local/scripts/config-switch b/config/scripts/.local/scripts/config-switch
--- a/config/scripts/.local/scripts/config-switch
+++ b/config/scripts/.local/scripts/config-switch
@@ -1,27 +1,29 @@
 #!/usr/bin/env bash
 
-path="$(dirname "$(readlink -f "$0")")"
-
 if [ -z "$1" ]; then
     desktop="$XDG_CURRENT_DESKTOP"
 else
     desktop="$1"
 fi
 
-config_path="$path/../../.."
-
 for item in "kitty" "ghostty" "wlogout"; do
-    for target in "$item" "$item-niri"; do
-        if [ ! -L "$HOME/.config/$target" ] && [ -e "$HOME/.config/$target" ]; then
-            echo "Error: $HOME/.config/$target exists and is not a symlink." >&2
+    if [ ! -L "$HOME/.config/$item" ] && [ -e "$HOME/.config/$item" ]; then
+        echo "Error: $HOME/.config/$item exists and is not a symlink." >&2
+        exit 1
+    elif [ -L "$HOME/.config/$item" ]; then
+        rm "$HOME/.config/$item" || {
+            echo "Error: Failed to remove existing symlink $HOME/.config/$item." >&2
             exit 1
-        fi
-        stow -t "$HOME" -d "$config_path" -D "$target"
-    done
+        }
+    fi
 
     if [ "$desktop" = "niri" ] || [ "$desktop" = "GNOME" ]; then
-        stow -t "$HOME" -d "$config_path" "$item-niri"
+        if [ -e "$HOME/.config/.alt/${item}-niri" ]; then
+            ln -svf ".alt/${item}-niri" "$HOME/.config/$item"
+        elif [ -e "$HOME/.config/.alt/${item}-default" ]; then
+            ln -svf ".alt/${item}-default" "$HOME/.config/$item"
+        fi
     else
-        stow -t "$HOME" -d "$config_path" "$item"
+        [ -e "$HOME/.config/.alt/${item}-default" ]  && ln -svf ".alt/${item}-default" "$HOME/.config/$item"
     fi
 done
