scripts: deleted 2 & added config-load & edited some

diff --git a/scripts/change-wallpaper b/scripts/change-wallpaper
--- a/scripts/change-wallpaper
+++ b/scripts/change-wallpaper
@@ -1,6 +1,28 @@
 #!/usr/bin/env bash
 
-# Select image file if none is provided
+# Required tools:
+# - zenity (for file selection dialog)
+# - imagemagick (for image processing)
+# - swww (wallpaper daemon)
+# - notify-send (for notifications)
+# - change-colortheme (from scripts/change-colortheme)
+# - flock (usually part of util-linux)
+
+# Lock
+
+exec {LOCK_FD}>/tmp/"$(basename "$0")".lock || {
+    echo "Failed to open lock file"
+    exit 1
+}
+
+flock -n "$LOCK_FD" || {
+    echo "Another instance is running. Exiting."
+    notify-send -a "change-wallpaper" "Error" "Another instance is running. Exiting."
+    exit 1
+}
+
+# Open a file selection dialog if no argument is provided
+
 if [ -z "$1" ]; then
     image=$(zenity --file-selection --title="Open File" --file-filter="*.jpg *.jpeg *.png *.webp *.bmp *.jfif *.tiff *.avif *.heic *.heif")
 else
diff --git a/scripts/config-switch b/scripts/config-switch
--- a/scripts/config-switch
+++ b/scripts/config-switch
@@ -9,13 +9,18 @@ else
 fi
 
 for item in "kitty" "ghostty" "wlogout"; do
-    [ -L "$HOME/.config/$item" ] || exit 1
-
-    rm "$HOME/.config/$item"
+    for target in "$item" "$item-niri"; do
+        if [ -L "$HOME/.config/$target" ]; then
+            rm -v "$HOME/.config/$target"
+        elif [ -e "$HOME/.config/$target" ]; then
+            echo "Error: $HOME/.config/$target is not a symlink." >&2
+            exit 1
+        fi
+    done
 
     if [ "$desktop" = "niri" ]; then
-        ln -s "$path/../config/$item-niri" "$HOME/.config/$item"
+        ln -sv "$path/../config/$item-niri" "$HOME/.config/$item"
     else
-        ln -s "$path/../config/$item" "$HOME/.config/$item"
+        ln -sv "$path/../config/$item" "$HOME/.config/$item"
     fi
 done
